# Assembly generated by llc (l-lang compiler)

.text
.globl _start
_start:
        jal     main
        li      $v0, 10
        syscall

malloc:
        li      $v0, 9
        syscall
        jr      $ra

strcpyn:
        addiu   $sp, $sp, -16
        sw      $a0, 0($sp)
        sw      $a1, 4($sp)
        sw      $a2, 8($sp)
        li      $t0, 0
        sw      $t0, 12($sp)
        j       L5
L4:
        lw      $t0, 0($sp)
        lw      $t1, 12($sp)
        add     $t2, $t0, $t1
        lw      $t1, 4($sp)
        lw      $t0, 12($sp)
        add     $t3, $t1, $t0
        lb      $t4, 0($t3)
        sb      $t4, 0($t2)
        lw      $t0, 12($sp)
        li      $t1, 1
        add     $t2, $t0, $t1
        sw      $t2, 12($sp)
L5:
        lw      $t0, 4($sp)
        lw      $t1, 12($sp)
        add     $t2, $t0, $t1
        lb      $t3, 0($t2)
        li      $t2, 0
        sne     $t1, $t3, $t2
        lw      $t2, 12($sp)
        lw      $t3, 8($sp)
        slt     $t0, $t2, $t3
        and     $t3, $t1, $t0
        bnez    $t3, L4
        addiu   $sp, $sp, 16
        jr      $ra

person_new:
        addiu   $sp, $sp, -16
        sw      $ra, 12($sp)
        sw      $a0, 0($sp)
        sb      $a1, 4($sp)
        li      $t0, 36
        move    $a0, $t0
        jal     malloc
        move    $t1, $v0
        sw      $t1, 8($sp)
        lw      $t0, 8($sp)
        move    $a0, $t0
        lw      $t1, 0($sp)
        move    $a1, $t1
        li      $t2, 32
        move    $a2, $t2
        jal     strcpyn
        lw      $t0, 8($sp)
        li      $t1, 32
        add     $t2, $t0, $t1
        lb      $t1, 4($sp)
        sb      $t1, 0($t2)
        lw      $t0, 8($sp)
        move    $v0, $t0
        lw      $ra, 12($sp)
        addiu   $sp, $sp, 16
        jr      $ra

person_init:
        addiu   $sp, $sp, -16
        sw      $ra, 12($sp)
        sw      $a0, 0($sp)
        sw      $a1, 4($sp)
        sb      $a2, 8($sp)
        lw      $t0, 0($sp)
        move    $a0, $t0
        lw      $t1, 4($sp)
        move    $a1, $t1
        li      $t2, 32
        move    $a2, $t2
        jal     strcpyn
        lw      $t0, 0($sp)
        li      $t1, 32
        add     $t2, $t0, $t1
        lb      $t1, 8($sp)
        sb      $t1, 0($t2)
        lw      $ra, 12($sp)
        addiu   $sp, $sp, 16
        jr      $ra

main:
        addiu   $sp, $sp, -72
        sw      $ra, 40($sp)
        addiu   $t0, $sp, 44
        li      $t1, 75
        sb      $t1, 0($t0)
        li      $t1, 114
        li      $t2, 1
        add     $t3, $t0, $t2
        sb      $t1, 0($t3)
        li      $t1, 105
        li      $t3, 2
        add     $t2, $t0, $t3
        sb      $t1, 0($t2)
        li      $t1, 115
        li      $t2, 3
        add     $t3, $t0, $t2
        sb      $t1, 0($t3)
        li      $t1, 32
        li      $t3, 4
        add     $t2, $t0, $t3
        sb      $t1, 0($t2)
        li      $t1, 40
        li      $t2, 5
        add     $t3, $t0, $t2
        sb      $t1, 0($t3)
        li      $t1, 72
        li      $t3, 6
        add     $t2, $t0, $t3
        sb      $t1, 0($t2)
        li      $t1, 101
        li      $t2, 7
        add     $t3, $t0, $t2
        sb      $t1, 0($t3)
        li      $t1, 97
        li      $t3, 8
        add     $t2, $t0, $t3
        sb      $t1, 0($t2)
        li      $t1, 112
        li      $t2, 9
        add     $t3, $t0, $t2
        sb      $t1, 0($t3)
        li      $t1, 41
        li      $t3, 10
        add     $t2, $t0, $t3
        sb      $t1, 0($t2)
        li      $t1, 0
        li      $t2, 11
        add     $t3, $t0, $t2
        sb      $t1, 0($t3)
        move    $a0, $t0
        li      $t1, 14
        move    $a1, $t1
        jal     person_new
        move    $t3, $v0
        sw      $t3, 0($sp)
        addiu   $t0, $sp, 4
        move    $a0, $t0
        addiu   $t1, $sp, 56
        li      $t2, 77
        sb      $t2, 0($t1)
        li      $t2, 105
        li      $t3, 1
        add     $t4, $t1, $t3
        sb      $t2, 0($t4)
        li      $t2, 107
        li      $t4, 2
        add     $t3, $t1, $t4
        sb      $t2, 0($t3)
        li      $t2, 101
        li      $t3, 3
        add     $t4, $t1, $t3
        sb      $t2, 0($t4)
        li      $t2, 32
        li      $t4, 4
        add     $t3, $t1, $t4
        sb      $t2, 0($t3)
        li      $t2, 40
        li      $t3, 5
        add     $t4, $t1, $t3
        sb      $t2, 0($t4)
        li      $t2, 83
        li      $t4, 6
        add     $t3, $t1, $t4
        sb      $t2, 0($t3)
        li      $t2, 116
        li      $t3, 7
        add     $t4, $t1, $t3
        sb      $t2, 0($t4)
        li      $t2, 97
        li      $t4, 8
        add     $t3, $t1, $t4
        sb      $t2, 0($t3)
        li      $t2, 99
        li      $t3, 9
        add     $t4, $t1, $t3
        sb      $t2, 0($t4)
        li      $t2, 107
        li      $t4, 10
        add     $t3, $t1, $t4
        sb      $t2, 0($t3)
        li      $t2, 41
        li      $t3, 11
        add     $t4, $t1, $t3
        sb      $t2, 0($t4)
        li      $t2, 0
        li      $t4, 12
        add     $t3, $t1, $t4
        sb      $t2, 0($t3)
        move    $a1, $t1
        li      $t2, 42
        move    $a2, $t2
        jal     person_init
        lw      $ra, 40($sp)
        addiu   $sp, $sp, 72
        jr      $ra

