# Assembly generated by llc (l-lang compiler)

.globl _start
_start:
        jal     main
        li      $v0, 10
        syscall

println_i32:
        addiu   $sp, $sp, -8
        sw      $a0, 0($sp)
        li      $v0, 1
        syscall
        li      $a0, 10
        li      $v0, 11
        syscall
        addiu   $sp, $sp, 8
        jr      $ra

printarr_i32:
        addiu   $sp, $sp, -16
        sw      $ra, 12($sp)
        sw      $a0, 0($sp)
        sw      $a1, 4($sp)
        li      $t0, 0
        sw      $t0, 8($sp)
        j       L1
L0:
        lw      $t0, 0($sp)
        lw      $t1, 8($sp)
        li      $t4, 4
        mul     $t3, $t1, $t4
        add     $t2, $t0, $t3
        lw      $t4, 0($t2)
        move    $a0, $t4
        jal     println_i32
        lw      $t0, 8($sp)
        li      $t1, 1
        add     $t2, $t0, $t1
        sw      $t2, 8($sp)
L1:
        lw      $t0, 8($sp)
        lw      $t1, 4($sp)
        slt     $t2, $t0, $t1
        bnez    $t2, L0
        lw      $ra, 12($sp)
        addiu   $sp, $sp, 16
        jr      $ra

swap:
        addiu   $sp, $sp, -16
        sw      $a0, 0($sp)
        sw      $a1, 4($sp)
        lw      $t0, 0($sp)
        lw      $t1, 0($t0)
        sw      $t1, 8($sp)
        lw      $t0, 0($sp)
        lw      $t1, 4($sp)
        lw      $t2, 0($t1)
        sw      $t2, 0($t0)
        lw      $t0, 4($sp)
        lw      $t1, 8($sp)
        sw      $t1, 0($t0)
        addiu   $sp, $sp, 16
        jr      $ra

partition:
        addiu   $sp, $sp, -32
        sw      $ra, 24($sp)
        sw      $a0, 0($sp)
        sw      $a1, 4($sp)
        sw      $a2, 8($sp)
        lw      $t0, 0($sp)
        lw      $t1, 8($sp)
        li      $t4, 4
        mul     $t3, $t1, $t4
        add     $t2, $t0, $t3
        lw      $t4, 0($t2)
        sw      $t4, 12($sp)
        lw      $t0, 4($sp)
        li      $t1, 1
        sub     $t2, $t0, $t1
        sw      $t2, 16($sp)
        lw      $t0, 4($sp)
        sw      $t0, 20($sp)
        j       L4
L3:
        lw      $t0, 0($sp)
        lw      $t1, 20($sp)
        li      $t4, 4
        mul     $t3, $t1, $t4
        add     $t2, $t0, $t3
        lw      $t4, 0($t2)
        lw      $t2, 12($sp)
        slt     $t1, $t4, $t2
        beqz    $t1, L2
        lw      $t0, 16($sp)
        li      $t1, 1
        add     $t2, $t0, $t1
        sw      $t2, 16($sp)
        lw      $t0, 0($sp)
        lw      $t1, 16($sp)
        li      $t4, 4
        mul     $t3, $t1, $t4
        add     $t2, $t0, $t3
        move    $a0, $t2
        lw      $t4, 0($sp)
        lw      $t3, 20($sp)
        li      $t5, 4
        mul     $t0, $t3, $t5
        add     $t1, $t4, $t0
        move    $a1, $t1
        jal     swap
        j       L2
L2:
        lw      $t0, 20($sp)
        li      $t1, 1
        add     $t2, $t0, $t1
        sw      $t2, 20($sp)
L4:
        lw      $t0, 20($sp)
        lw      $t1, 8($sp)
        sle     $t2, $t0, $t1
        bnez    $t2, L3
        lw      $t0, 0($sp)
        lw      $t1, 16($sp)
        li      $t2, 1
        add     $t3, $t1, $t2
        li      $t4, 4
        mul     $t1, $t3, $t4
        add     $t2, $t0, $t1
        move    $a0, $t2
        lw      $t4, 0($sp)
        lw      $t1, 8($sp)
        li      $t5, 4
        mul     $t0, $t1, $t5
        add     $t3, $t4, $t0
        move    $a1, $t3
        jal     swap
        lw      $t0, 16($sp)
        li      $t1, 1
        add     $t2, $t0, $t1
        move    $v0, $t2
        lw      $ra, 24($sp)
        addiu   $sp, $sp, 32
        jr      $ra

quick_sort:
        addiu   $sp, $sp, -24
        sw      $ra, 16($sp)
        sw      $a0, 0($sp)
        sw      $a1, 4($sp)
        sw      $a2, 8($sp)
        lw      $t0, 4($sp)
        lw      $t1, 8($sp)
        slt     $t2, $t0, $t1
        beqz    $t2, L5
        lw      $t0, 0($sp)
        move    $a0, $t0
        lw      $t1, 4($sp)
        move    $a1, $t1
        lw      $t2, 8($sp)
        move    $a2, $t2
        jal     partition
        move    $t3, $v0
        sw      $t3, 12($sp)
        lw      $t0, 0($sp)
        move    $a0, $t0
        lw      $t1, 4($sp)
        move    $a1, $t1
        lw      $t2, 12($sp)
        li      $t3, 1
        sub     $t4, $t2, $t3
        move    $a2, $t4
        jal     quick_sort
        lw      $t0, 0($sp)
        move    $a0, $t0
        lw      $t1, 12($sp)
        li      $t2, 1
        add     $t3, $t1, $t2
        move    $a1, $t3
        lw      $t2, 8($sp)
        move    $a2, $t2
        jal     quick_sort
        j       L5
L5:
        lw      $ra, 16($sp)
        addiu   $sp, $sp, 24
        jr      $ra

main:
        addiu   $sp, $sp, -48
        sw      $ra, 4($sp)
        addiu   $t0, $sp, 8
        li      $t1, 7
        sw      $t1, 0($t0)
        li      $t1, 3
        li      $t2, 4
        add     $t3, $t0, $t2
        sw      $t1, 0($t3)
        li      $t1, 4
        li      $t3, 8
        add     $t2, $t0, $t3
        sw      $t1, 0($t2)
        li      $t1, 2
        li      $t2, 12
        add     $t3, $t0, $t2
        sw      $t1, 0($t3)
        li      $t1, 9
        li      $t3, 16
        add     $t2, $t0, $t3
        sw      $t1, 0($t2)
        li      $t1, 8
        li      $t2, 20
        add     $t3, $t0, $t2
        sw      $t1, 0($t3)
        li      $t1, 0
        li      $t3, 24
        add     $t2, $t0, $t3
        sw      $t1, 0($t2)
        li      $t1, 1
        li      $t2, 28
        add     $t3, $t0, $t2
        sw      $t1, 0($t3)
        li      $t1, 5
        li      $t3, 32
        add     $t2, $t0, $t3
        sw      $t1, 0($t2)
        li      $t1, 6
        li      $t2, 36
        add     $t3, $t0, $t2
        sw      $t1, 0($t3)
        sw      $t0, 0($sp)
        lw      $t0, 0($sp)
        move    $a0, $t0
        li      $t1, 0
        move    $a1, $t1
        li      $t2, 9
        move    $a2, $t2
        jal     quick_sort
        lw      $t0, 0($sp)
        move    $a0, $t0
        li      $t1, 10
        move    $a1, $t1
        jal     printarr_i32
        lw      $ra, 4($sp)
        addiu   $sp, $sp, 48
        jr      $ra

