# Assembly generated by llc (l-lang compiler)

.globl _start
_start:
        jal     main
        li      $v0, 10
        syscall

read_i32:
        li      $v0, 5
        syscall
        jr      $ra

println_i32:
        addiu   $sp, $sp, -8
        sw      $a0, 0($sp)
        li      $v0, 1
        syscall
        li      $a0, 10
        li      $v0, 11
        syscall
        addiu   $sp, $sp, 8
        jr      $ra

main:
        addiu   $sp, $sp, -8
        sw      $ra, 4($sp)
        jal     read_i32
        move    $t0, $v0
        sw      $t0, 0($sp)
        lw      $t1, 0($sp)
        li      $t2, 1
        add     $t3, $t1, $t2
        move    $a0, $t3
        jal     println_i32
        lw      $ra, 4($sp)
        addiu   $sp, $sp, 8
        jr      $ra

