# Assembly generated by llc (l-lang compiler)

.globl _start
_start:
        jal     main
        li      $v0, 10
        syscall

plus1:
        addiu   $sp, $sp, -8
        sw      $a0, 0($sp)
        lw      $t0, 0($sp)
        li      $t1, 1
        add     $t2, $t0, $t1
        move    $v0, $t2
        addiu   $sp, $sp, 8
        jr      $ra

main:
        addiu   $sp, $sp, -16
        sw      $ra, 12($sp)
        li      $t1, 41
        sw      $t1, 0($sp)
        lw      $t0, 0($sp)
        move    $a0, $t0
        jal     plus1
        move    $t0, $v0
        sw      $t0, 4($sp)
        li      $t1, 1
        move    $a0, $t1
        jal     plus1
        move    $t2, $v0
        li      $t3, 2
        add     $t4, $t2, $t3
        sh      $t4, 8($sp)
        lw      $ra, 12($sp)
        addiu   $sp, $sp, 16
        jr      $ra

