# Assembly generated by lcc (l-lang compiler)

.globl _start
_start:
        jal     main
        li      $v0, 10
        syscall

main:
        addiu   $sp, $sp, -8
        li      $t0, 42
        sw      $t0, 0($sp)
        lw      $t0, 0($sp)
        sw      $t0, 4($sp)
        addiu   $sp, $sp, 8
        jr      $ra
        
