# Assembly generated by llc (l-lang compiler)

.globl _start
_start:
        jal     main
        li      $v0, 10
        syscall

println_i32:
        addiu   $sp, $sp, -8
        sw      $a0, 0($sp)
        li      $v0, 1
        syscall
        li      $a0, 10
        li      $v0, 11
        syscall
        addiu   $sp, $sp, 8
        jr      $ra

main:
        addiu   $sp, $sp, -16
        sw      $ra, 12($sp)
        j       L3
L2:
        li      $t0, 0
        sw      $t0, 0($sp)
        li      $t0, 1
        sw      $t0, 4($sp)
        j       L1
L0:
        lw      $t0, 0($sp)
        move    $a0, $t0
        jal     println_i32
        lw      $t0, 0($sp)
        lw      $t1, 4($sp)
        add     $t2, $t0, $t1
        sw      $t2, 8($sp)
        lw      $t0, 4($sp)
        sw      $t0, 0($sp)
        lw      $t0, 8($sp)
        sw      $t0, 4($sp)
L1:
        lw      $t0, 0($sp)
        li      $t1, 255
        slt     $t2, $t0, $t1
        bnez    $t2, L0
L3:
        li      $t0, 1
        bnez    $t0, L2
        lw      $ra, 12($sp)
        addiu   $sp, $sp, 16
        jr      $ra

