# Assembly generated by llc (l-lang compiler)

.data
str0: .asciiz "["
str1: .asciiz "%d, "
str2: .asciiz "%d"
str3: .asciiz "]\n"
str4: .asciiz "Vec len: %d\n"
str5: .asciiz "Vec cap: %d\n"

.text
.globl _start
_start:
        jal     main
        li      $v0, 10
        syscall

print_i32:
        li      $v0, 1
        syscall
        jr      $ra

print_str:
        li      $v0, 4
        syscall
        jr      $ra

print_char:
        li      $v0, 11
        syscall
        jr      $ra

print_ptr:
        li      $v0, 34
        syscall
        jr      $ra

printf:
        addiu   $sp, $sp, -32
        sw      $ra, 0($sp)
        sw      $a0, 4($sp)
        sw      $a1, 8($sp)
        j       L12
L11:
        lw      $t0, 4($sp)
        lb      $t1, 0($t0)
        li      $t0, 37
        seq     $t2, $t1, $t0
        beqz    $t2, L9
        lw      $t0, 4($sp)
        li      $t1, 1
        add     $t2, $t0, $t1
        sw      $t2, 4($sp)
        lw      $t0, 4($sp)
        lb      $t1, 0($t0)
        li      $t0, 100
        seq     $t2, $t1, $t0
        beqz    $t2, L7
        lw      $t0, 8($sp)
        sw      $t0, 12($sp)
        lw      $t0, 12($sp)
        move    $a0, $t0
        jal     print_i32
        j       L8
L7:
        lw      $t0, 4($sp)
        lb      $t1, 0($t0)
        li      $t0, 115
        seq     $t2, $t1, $t0
        beqz    $t2, L5
        lw      $t0, 8($sp)
        sw      $t0, 16($sp)
        lw      $t0, 16($sp)
        move    $a0, $t0
        jal     print_str
        j       L6
L5:
        lw      $t0, 4($sp)
        lb      $t1, 0($t0)
        li      $t0, 99
        seq     $t2, $t1, $t0
        beqz    $t2, L3
        lw      $t0, 8($sp)
        sb      $t0, 20($sp)
        lb      $t0, 20($sp)
        move    $a0, $t0
        jal     print_char
        j       L4
L3:
        lw      $t0, 4($sp)
        lb      $t1, 0($t0)
        li      $t0, 112
        seq     $t2, $t1, $t0
        beqz    $t2, L1
        lw      $t0, 8($sp)
        sw      $t0, 24($sp)
        lw      $t0, 24($sp)
        move    $a0, $t0
        jal     print_ptr
        j       L2
L1:
        lw      $t0, 4($sp)
        lb      $t1, 0($t0)
        li      $t0, 37
        seq     $t2, $t1, $t0
        beqz    $t2, L0
        li      $t0, 37
        sb      $t0, 28($sp)
        lb      $t0, 28($sp)
        move    $a0, $t0
        jal     print_char
        j       L0
L0:
        j       L2
L2:
        j       L4
L4:
        j       L6
L6:
        j       L8
L8:
        j       L10
L9:
        lw      $t0, 4($sp)
        lb      $t1, 0($t0)
        move    $a0, $t1
        jal     print_char
        j       L10
L10:
        lw      $t0, 4($sp)
        li      $t1, 1
        add     $t2, $t0, $t1
        sw      $t2, 4($sp)
L12:
        lw      $t0, 4($sp)
        lb      $t1, 0($t0)
        li      $t0, 0
        sne     $t2, $t1, $t0
        bnez    $t2, L11
        lw      $ra, 0($sp)
        addiu   $sp, $sp, 32
        jr      $ra

malloc:
        li      $v0, 9
        syscall
        jr      $ra

vec_init:
        addiu   $sp, $sp, -16
        sw      $ra, 0($sp)
        sw      $a0, 4($sp)
        lw      $t0, 4($sp)
        sw      $t0, 8($sp)
        li      $t2, 4
        move    $a0, $t2
        jal     malloc
        move    $t2, $v0
        lw      $t1, 8($sp)
        sw      $t2, 0($t1)
        lw      $t0, 4($sp)
        li      $t1, 4
        add     $t2, $t0, $t1
        li      $t1, 0
        sw      $t1, 0($t2)
        lw      $t0, 4($sp)
        li      $t1, 8
        add     $t2, $t0, $t1
        li      $t1, 1
        sw      $t1, 0($t2)
        lw      $ra, 0($sp)
        addiu   $sp, $sp, 16
        jr      $ra

push:
        addiu   $sp, $sp, -24
        sw      $ra, 0($sp)
        sw      $a0, 4($sp)
        sw      $a1, 8($sp)
        lw      $t0, 4($sp)
        li      $t1, 4
        add     $t2, $t0, $t1
        lw      $t1, 0($t2)
        lw      $t2, 4($sp)
        li      $t0, 8
        add     $t3, $t2, $t0
        lw      $t0, 0($t3)
        seq     $t3, $t1, $t0
        beqz    $t3, L24
        lw      $t0, 4($sp)
        li      $t1, 8
        add     $t2, $t0, $t1
        lw      $t1, 0($t2)
        li      $t2, 2
        mul     $t0, $t1, $t2
        sw      $t0, 12($sp)
        li      $t0, 4
        lw      $t1, 12($sp)
        mul     $t2, $t0, $t1
        move    $a0, $t2
        jal     malloc
        move    $t2, $v0
        sw      $t2, 16($sp)
        li      $t0, 0
        sw      $t0, 20($sp)
        j       L23
L22:
        lw      $t0, 16($sp)
        lw      $t1, 20($sp)
        li      $t4, 4
        mul     $t3, $t1, $t4
        add     $t2, $t0, $t3
        lw      $t1, 4($sp)
        lw      $t0, 0($t1)
        lw      $t1, 20($sp)
        li      $t5, 4
        mul     $t3, $t1, $t5
        add     $t4, $t0, $t3
        lw      $t5, 0($t4)
        sw      $t5, 0($t2)
        lw      $t0, 20($sp)
        li      $t1, 1
        add     $t2, $t0, $t1
        sw      $t2, 20($sp)
L23:
        lw      $t0, 20($sp)
        lw      $t1, 4($sp)
        li      $t2, 8
        add     $t3, $t1, $t2
        lw      $t2, 0($t3)
        slt     $t3, $t0, $t2
        bnez    $t3, L22
        lw      $t0, 4($sp)
        lw      $t1, 16($sp)
        sw      $t1, 0($t0)
        lw      $t0, 4($sp)
        li      $t1, 8
        add     $t2, $t0, $t1
        lw      $t1, 12($sp)
        sw      $t1, 0($t2)
        j       L24
L24:
        lw      $t0, 4($sp)
        lw      $t1, 0($t0)
        lw      $t0, 4($sp)
        li      $t2, 4
        add     $t3, $t0, $t2
        lw      $t2, 0($t3)
        li      $t4, 4
        mul     $t0, $t2, $t4
        add     $t3, $t1, $t0
        lw      $t2, 8($sp)
        sw      $t2, 0($t3)
        lw      $t0, 4($sp)
        li      $t1, 4
        add     $t2, $t0, $t1
        lw      $t1, 4($sp)
        li      $t0, 4
        add     $t3, $t1, $t0
        lw      $t0, 0($t3)
        li      $t3, 1
        add     $t1, $t0, $t3
        sw      $t1, 0($t2)
        lw      $ra, 0($sp)
        addiu   $sp, $sp, 24
        jr      $ra

print_vec:
        addiu   $sp, $sp, -16
        sw      $ra, 0($sp)
        sw      $a0, 4($sp)
        la      $t1, str0
        move    $a0, $t1
        jal     print_str
        lw      $t0, 4($sp)
        li      $t1, 4
        add     $t2, $t0, $t1
        lw      $t1, 0($t2)
        li      $t2, 0
        sgt     $t0, $t1, $t2
        beqz    $t0, L27
        li      $t0, 0
        sw      $t0, 8($sp)
        j       L26
L25:
        la      $t1, str1
        move    $a0, $t1
        lw      $t1, 4($sp)
        lw      $t2, 0($t1)
        lw      $t1, 8($sp)
        li      $t5, 4
        mul     $t4, $t1, $t5
        add     $t3, $t2, $t4
        lw      $t5, 0($t3)
        move    $a1, $t5
        jal     printf
        lw      $t0, 8($sp)
        li      $t1, 1
        add     $t2, $t0, $t1
        sw      $t2, 8($sp)
L26:
        lw      $t0, 8($sp)
        lw      $t1, 4($sp)
        li      $t2, 4
        add     $t3, $t1, $t2
        lw      $t2, 0($t3)
        li      $t3, 1
        sub     $t1, $t2, $t3
        slt     $t3, $t0, $t1
        bnez    $t3, L25
        la      $t1, str2
        move    $a0, $t1
        lw      $t1, 4($sp)
        lw      $t2, 0($t1)
        lw      $t1, 4($sp)
        li      $t3, 4
        add     $t4, $t1, $t3
        lw      $t3, 0($t4)
        li      $t4, 1
        sub     $t1, $t3, $t4
        li      $t5, 4
        mul     $t3, $t1, $t5
        add     $t4, $t2, $t3
        lw      $t5, 0($t4)
        move    $a1, $t5
        jal     printf
        j       L27
L27:
        la      $t1, str3
        move    $a0, $t1
        jal     print_str
        lw      $ra, 0($sp)
        addiu   $sp, $sp, 16
        jr      $ra

main:
        addiu   $sp, $sp, -16
        sw      $ra, 0($sp)
        addiu   $t0, $sp, 4
        move    $a0, $t0
        jal     vec_init
        addiu   $t0, $sp, 4
        move    $a0, $t0
        li      $t0, 1
        move    $a1, $t0
        jal     push
        addiu   $t0, $sp, 4
        move    $a0, $t0
        li      $t0, 2
        move    $a1, $t0
        jal     push
        addiu   $t0, $sp, 4
        move    $a0, $t0
        li      $t0, 3
        move    $a1, $t0
        jal     push
        addiu   $t0, $sp, 4
        move    $a0, $t0
        li      $t0, 4
        move    $a1, $t0
        jal     push
        addiu   $t0, $sp, 4
        move    $a0, $t0
        jal     print_vec
        la      $t1, str4
        move    $a0, $t1
        addiu   $t1, $sp, 4
        li      $t2, 4
        add     $t3, $t1, $t2
        lw      $t2, 0($t3)
        move    $a1, $t2
        jal     printf
        la      $t1, str5
        move    $a0, $t1
        addiu   $t1, $sp, 4
        li      $t2, 8
        add     $t3, $t1, $t2
        lw      $t2, 0($t3)
        move    $a1, $t2
        jal     printf
        lw      $ra, 0($sp)
        addiu   $sp, $sp, 16
        jr      $ra

