use crate::allocator::Allocator;
use ir::{
    instruction::{BranchType, IrFunction, IrInstruction, IrReg, IrType, IrValue},
    program::IrProgram,
};
use parser::expression::{BinaryOperator, UnaryOperator};
use semantic::symbol::SymbolId;

pub struct Mips {
    program: IrProgram,
    compiled: String,
}

impl Mips {
    pub fn new(program: IrProgram) -> Self {
        Self {
            program,
            compiled: String::new(),
        }
    }

    pub fn generate(&mut self) -> String {
        self.compiled
            .push_str("# Assembly generated by llc (l-lang compiler)\n\n");

        if !self.program.strings.is_empty() {
            self.compiled.push_str(".data\n");
            for (label, content) in &self.program.strings.clone() {
                self.compiled
                    .push_str(&format!("{}: .asciiz \"{}\"\n", label, content));
            }
            self.compiled.push_str("\n");
        }

        self.compiled.push_str(".text\n");

        let has_main = self.program.functions.iter().any(|f| f.name == "main");

        if has_main {
            self.compiled.push_str(".globl _start\n");
            self.compiled.push_str("_start:\n");
            self.emit_instruction("jal", "main");
            self.emit_instruction("li", "$v0, 10");
            self.emit_instruction("syscall", "");
            self.compiled.push_str("\n");
        }

        for func in self.program.functions.clone() {
            self.generate_function(func);
        }

        self.compiled.clone()
    }

    fn generate_function(&mut self, ir_function: IrFunction) {
        let instructions = ir_function.instructions;

        let mut allocator = Allocator::new();
        self.init_stack(&instructions, &mut allocator);

        for instr in &instructions {
            if let IrInstruction::SpillTemp { slot, .. } = instr {
                allocator.get_or_insert_spill(*slot);
            }
        }

        allocator.align8();

        self.emit_label(&ir_function.name);

        let stack_size = allocator.get_stack_size();

        if stack_size > 0 {
            self.emit_instruction("addiu", &format!("$sp, $sp, -{}", stack_size));
        }

        if let Some(ra_offset) = allocator.get_ra_offset() {
            self.emit_instruction("sw", &format!("$ra, {}($sp)", ra_offset));
        }

        for instr in instructions {
            self.generate_instruction(instr, &mut allocator);
        }
    }

    fn generate_instruction(&mut self, instr: IrInstruction, allocator: &mut Allocator) {
        match instr {
            IrInstruction::SaveRa => return,
            IrInstruction::Alloc { .. } => return,
            IrInstruction::StoreImm { dest, value } => self.generate_store_imm(dest, value),

            IrInstruction::StoreStack {
                ir_type,
                symbol,
                src,
            } => self.generate_store_stack(ir_type, symbol, src, allocator),

            IrInstruction::LoadStack {
                ir_type,
                dest,
                symbol,
            } => self.generate_load_stack(ir_type, dest, symbol, allocator),

            IrInstruction::Call { function_name } => {
                self.emit_instruction("jal", &function_name);
            }

            IrInstruction::Label { label_name } => self.emit_label(&label_name),
            IrInstruction::Jump { label } => self.emit_instruction("j", &label),

            IrInstruction::Branch {
                reg,
                label,
                branch_type,
            } => {
                let instr = match branch_type {
                    BranchType::EqZero => "beqz",
                    BranchType::NeqZero => "bnez",
                };
                self.emit_instruction(instr, &format!("{}, {}", reg, label));
            }

            IrInstruction::SpillTemp { slot, src } => {
                let offset = allocator.get_or_insert_spill(slot);
                self.emit_instruction("sw", &format!("{}, {}($sp)", src, offset));
            }

            IrInstruction::LoadTemp { slot, dest } => {
                let offset = allocator.get_or_insert_spill(slot);
                self.emit_instruction("lw", &format!("{}, {}($sp)", dest, offset));
            }

            IrInstruction::Ret => self.generate_return(allocator),

            IrInstruction::BinaryOp {
                op,
                dest,
                left,
                right,
            } => self.generate_binary_op(op, dest, left, right),

            IrInstruction::UnaryOp { op, dest, operand } => match op {
                UnaryOperator::Not => {
                    self.emit_instruction("seq", &format!("{}, {}, $zero", dest, operand));
                }

                UnaryOperator::Deref | UnaryOperator::AddressOf => {
                    unreachable!(
                        "Deref/AddressOf are lowered to LoadIndirect/LoadAddr, never UnaryOp"
                    )
                }
                UnaryOperator::Neg => {
                    self.emit_instruction("sub", &format!("{}, $zero, {}", dest, operand));
                }
            },

            IrInstruction::LoadAddr { dest, symbol } => {
                self.generate_load_addr(dest, symbol, allocator)
            }

            IrInstruction::LoadIndirect {
                ir_type,
                dest,
                addr,
            } => {
                self.emit_instruction(
                    &format!("l{}", ir_type.instruction()),
                    &format!("{}, 0({})", dest, addr),
                );
            }

            IrInstruction::StoreIndirect { ir_type, addr, src } => {
                self.emit_instruction(
                    &format!("s{}", ir_type.instruction()),
                    &format!("{}, 0({})", src, addr),
                );
            }

            IrInstruction::AllocArray { .. } => return,

            IrInstruction::LoadArrayBase { dest, slot } => {
                let offset = allocator.get_array_base_offset(slot);
                self.emit_instruction("addiu", &format!("{}, $sp, {}", dest, offset));
            }

            IrInstruction::AllocStruct { .. } => return,

            IrInstruction::LoadStringAddr { dest, label } => {
                self.emit_instruction("la", &format!("{}, {}", dest, label));
            }

            IrInstruction::LoadArgStack {
                ir_type,
                dest,
                offset,
            } => {
                let addr = allocator.get_stack_size() + offset;

                self.emit_instruction(
                    &format!("l{}", ir_type.instruction()),
                    &format!("{}, {}($sp)", dest, addr),
                );
            }

            IrInstruction::StoreArgStack {
                ir_type,
                offset,
                src,
            } => {
                let addr = offset;

                self.emit_instruction(
                    &format!("s{}", ir_type.instruction()),
                    &format!("{}, {}($sp)", src, addr),
                );
            }

            IrInstruction::Assembly { line } => self.emit_instruction(&line, ""),
        }
    }

    fn generate_load_addr(&mut self, dest: IrReg, symbol: SymbolId, allocator: &mut Allocator) {
        self.emit_instruction(
            "addiu",
            &format!("{}, $sp, {}", dest, allocator.get_variable_offset(&symbol)),
        );
    }

    fn generate_store_imm(&mut self, dest: IrReg, value: IrValue) {
        if let IrValue::Immediate(n) = value {
            self.emit_instruction("li", &format!("{}, {}", dest, n));
        } else if let IrValue::Reg(reg) = value {
            self.emit_instruction("move", &format!("{}, {}", dest, reg));
        }
    }

    fn generate_store_stack(
        &mut self,
        ir_type: IrType,
        symbol: SymbolId,
        src: IrReg,
        allocator: &mut Allocator,
    ) {
        self.emit_instruction(
            &format!("s{}", ir_type.instruction()),
            &format!("{}, {}($sp)", src, allocator.get_variable_offset(&symbol)),
        );
    }

    fn generate_load_stack(
        &mut self,
        ir_type: IrType,
        dest: IrReg,
        symbol: SymbolId,
        allocator: &mut Allocator,
    ) {
        self.emit_instruction(
            &format!("l{}", ir_type.instruction()),
            &format!("{}, {}($sp)", dest, allocator.get_variable_offset(&symbol)),
        );
    }

    fn generate_binary_op(&mut self, op: BinaryOperator, dest: IrReg, left: IrReg, right: IrReg) {
        if matches!(op, BinaryOperator::Div) {
            self.emit_instruction("div", &format!("{}, {}", left, right));
            self.emit_instruction("mflo", &format!("{}", dest));
            return;
        }

        let instr = match op {
            BinaryOperator::Add => "add",
            BinaryOperator::Sub => "sub",
            BinaryOperator::Mul => "mul",
            BinaryOperator::Eq => "seq",
            BinaryOperator::NotEq => "sne",
            BinaryOperator::Lt => "slt",
            BinaryOperator::Gt => "sgt",
            BinaryOperator::LtEq => "sle",
            BinaryOperator::GtEq => "sge",
            BinaryOperator::And => "and",
            BinaryOperator::Or => "or",
            BinaryOperator::Div => unreachable!(),
        };

        self.emit_instruction(instr, &format!("{}, {}, {}", dest, left, right));
    }

    fn generate_return(&mut self, allocator: &mut Allocator) {
        if let Some(ra_offset) = allocator.get_ra_offset() {
            self.emit_instruction("lw", &format!("$ra, {}($sp)", ra_offset));
        }
        if allocator.get_stack_size() > 0 {
            self.emit_instruction(
                "addiu",
                &format!("$sp, $sp, {}", allocator.get_stack_size()),
            );
        }
        self.emit_instruction("jr", "$ra");
        self.compiled.push('\n');
    }

    fn init_stack(&self, instructions: &[IrInstruction], allocator: &mut Allocator) {
        let mut outgoing_size = 0;
        for instr in instructions {
            if let IrInstruction::StoreArgStack { offset, .. } = instr {
                let end = offset + 4;
                if end > outgoing_size {
                    outgoing_size = end;
                }
            }
        }
        allocator.reserve_outgoing(outgoing_size);

        for instr in instructions {
            if matches!(instr, IrInstruction::SaveRa) {
                allocator.insert_ra();
            }
        }

        for instr in instructions {
            match instr {
                IrInstruction::Alloc { ir_type, symbol } => {
                    allocator.insert_variable(symbol, ir_type);
                }
                IrInstruction::AllocArray {
                    slot,
                    elem_type,
                    count,
                } => {
                    allocator.insert_array(*slot, elem_type.size_bytes(), *count);
                }
                IrInstruction::AllocStruct { symbol, size_bytes } => {
                    allocator.insert_struct(symbol, *size_bytes);
                }
                _ => {}
            }
        }
    }

    fn emit_instruction(&mut self, opcode: &str, operands: &str) {
        if operands.is_empty() {
            self.compiled.push_str(&format!("        {}\n", opcode));
        } else {
            self.compiled
                .push_str(&format!("        {:<8}{}\n", opcode, operands));
        }
    }

    fn emit_label(&mut self, label: &String) {
        self.compiled.push_str(label);
        self.compiled.push_str(":\n");
    }
}
