use crate::allocator::Allocator;
use ir::{
    instruction::{IrFunction, IrInstruction, IrReg, IrType, IrValue},
    program::IrProgram,
};
use parser::expression::BinaryOperator;
use semantic::symbol::SymbolId;

pub struct Mips {
    program: IrProgram,
    compiled: String,
}

impl Mips {
    pub fn new(program: IrProgram) -> Self {
        Self {
            program,
            compiled: String::new(),
        }
    }

    pub fn generate(&mut self) -> String {
        self.compiled
            .push_str("# Assembly generated by llc (l-lang compiler)\n\n");

        let has_main = self.program.functions.iter().any(|f| f.name == "main");

        if has_main {
            self.compiled.push_str(".globl _start\n");
            self.compiled.push_str("_start:\n");
            self.emit_instruction("jal", "main");
            self.emit_instruction("li", "$v0, 10");
            self.emit_instruction("syscall", "");
            self.compiled.push_str("\n");
        }

        for func in self.program.functions.clone() {
            self.generate_function(func);
        }

        self.compiled.clone()
    }

    fn generate_function(&mut self, ir_function: IrFunction) {
        let name = ir_function.name.clone(); // save before move

        let (allocs, rest): (Vec<IrInstruction>, Vec<IrInstruction>) = ir_function
            .instructions
            .into_iter()
            .partition(|i| matches!(i, IrInstruction::Alloc { .. } | IrInstruction::SaveRa));

        let mut allocator = Allocator::new();
        self.init_stack(allocs, &mut allocator);

        self.emit_label(&name);

        let stack_size = allocator.get_stack_size();
        if stack_size > 0 {
            self.emit_instruction("addiu", &format!("$sp, $sp, -{}", stack_size));
        }

        if let Some(ra_offset) = allocator.get_ra_offset() {
            self.emit_instruction("sw", &format!("$ra, {}($sp)", ra_offset));
        }

        for instr in rest {
            self.generate_instruction(instr, &mut allocator);
        }
    }

    fn generate_instruction(&mut self, instr: IrInstruction, allocator: &mut Allocator) {
        match instr {
            IrInstruction::SaveRa => return,
            IrInstruction::Alloc { .. } => return,
            IrInstruction::StoreImm { dest, value } => self.generate_store_imm(dest, value),
            IrInstruction::StoreStack {
                ir_type,
                symbol,
                src,
            } => self.generate_store_stack(ir_type, symbol, src, allocator),
            IrInstruction::LoadStack {
                ir_type,
                dest,
                symbol,
            } => self.generate_load_stack(ir_type, dest, symbol, allocator),
            IrInstruction::Call { function_name } => {
                self.emit_instruction("jal", &function_name);
            }
            IrInstruction::Ret => self.generate_return(allocator),
            IrInstruction::BinaryOp {
                op,
                dest,
                left,
                right,
            } => self.generate_binary_op(op, dest, left, right),
        }
    }

    fn generate_store_imm(&mut self, dest: IrReg, value: IrValue) {
        if let IrValue::Immediate(n) = value {
            self.emit_instruction("li", &format!("{}, {}", dest, n));
        } else if let IrValue::Reg(reg) = value {
            self.emit_instruction("move", &format!("{}, {}", dest, reg));
        }
    }

    fn generate_store_stack(
        &mut self,
        ir_type: IrType,
        symbol: SymbolId,
        src: IrReg,
        allocator: &mut Allocator,
    ) {
        self.emit_instruction(
            &format!("s{}", ir_type.instruction()),
            &format!("{}, {}($sp)", src, allocator.get_variable_offset(&symbol)),
        );
    }

    fn generate_load_stack(
        &mut self,
        ir_type: IrType,
        dest: IrReg,
        symbol: SymbolId,
        allocator: &mut Allocator,
    ) {
        self.emit_instruction(
            &format!("l{}", ir_type.instruction()),
            &format!("{}, {}($sp)", dest, allocator.get_variable_offset(&symbol)),
        );
    }

    fn generate_binary_op(&mut self, op: BinaryOperator, dest: IrReg, left: IrReg, right: IrReg) {
        let instr = match op {
            BinaryOperator::Add => "add",
            BinaryOperator::Sub => "sub",
            BinaryOperator::Mul => "mul",
            BinaryOperator::Div => "div",
        };

        if instr == "div" {
            panic!("div not implemented in mips.rs")
        }

        self.emit_instruction(instr, &format!("{}, {}, {}", dest, left, right));
    }

    fn generate_return(&mut self, allocator: &mut Allocator) {
        if let Some(ra_offset) = allocator.get_ra_offset() {
            self.emit_instruction("lw", &format!("$ra, {}($sp)", ra_offset));
        }
        if allocator.get_stack_size() > 0 {
            self.emit_instruction(
                "addiu",
                &format!("$sp, $sp, {}", allocator.get_stack_size()),
            );
        }
        self.emit_instruction("jr", "$ra");
        self.compiled.push('\n');
    }

    fn init_stack(&self, allocs: Vec<IrInstruction>, allocator: &mut Allocator) {
        for instr in &allocs {
            if let IrInstruction::Alloc { ir_type, symbol } = instr {
                allocator.insert_variable(symbol, ir_type);
            } else if let IrInstruction::SaveRa = instr {
                allocator.insert_ra();
            }
        }

        // align stack to 8 bytes once we finish allocation
        allocator.align8();
    }

    fn emit_instruction(&mut self, opcode: &str, operands: &str) {
        if operands.is_empty() {
            self.compiled.push_str(&format!("        {}\n", opcode));
        } else {
            self.compiled
                .push_str(&format!("        {:<8}{}\n", opcode, operands));
        }
    }

    fn emit_label(&mut self, label: &String) {
        self.compiled.push_str(label);
        self.compiled.push_str(":\n");
    }
}
